### ISSUE TITLE
2 script errors preventing script from running

### ISSUE THREAD

**Issue by buggerboy** [pplude/TronScriptEvo#12]
several attempts to run kept giving error about missing ")" on the end if a line and refused to run further investigation showed 2 missing ")" using power-shell ise i was able to fix script to get it to run missing  ")" are as follows line number 220 missing ")" at end of line also line 250 has same issue was able to fix both using power-shell ise script is now running flawlesly

**Comment by pplude** [comment]
Patch has been merged. Thanks!
