### ISSUE TITLE
Be more specific with commit messages

### ISSUE THREAD

**Issue by nemchik** [pplude/TronScriptEvo#4]
I know you are just getting this off the ground (looking good!) but please be more specific with commit messages. For example "Update Core.ps1" 72ecb3a0c54ede05eb7d3b79c5685bbf533508fe doesn't tell me what was actually changed when looking at the commit history. Trying to find what change may have caused behavior X will be very difficult if the commit message naming continues this trend.

Just my opinion though ;)

**Comment by nemchik** [comment]
I outlined some additional specifics about commit etiquette here https://github.com/bmrf/tron/issues/19

**Comment by pplude** [comment]
Not a problem. Going forward this is going to be a thing.
